repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.24.2
    hooks:
      - id: pdm-export
        name: Export requirements.txt
        args:
          - -o
          - requirements.txt
          - --prod
          - --without-hashes
          - --pyproject
        files: ^pdm.lock$        
        pass_filenames: false
        stages: [pre-commit]
      - id: pdm-export
        name: Export requirements_gui.txt
        args:
          - -o
          - requirements_gui.txt
          - --prod
          - --without-hashes
          - --pyproject
          - --with
          - gui
        files: ^pdm.lock$    
        pass_filenames: false
        stages: [pre-commit]