[video]
rotation_version = 2 # 直播模式版本
auto_crop = true # 是否裁剪到16:9
circle_crop = true # 是否圆形裁剪
display_all = true # 是否显示全部
background_need = true # 是否需要背景
window_size = 3 # 平滑参数
height = 0 # 输出视频高度（0 为自动判断）

[encode] # 编码器
codec = "hevc_nvenc" # 详细请查看
bitrate = "8m" # 8 Mbps

[other]
ask_for_config = true # 在直接运行时，是否询问
default_output_filename = "{}_out" # 默认输出文件名
ask_for_output = false # 是否需要询问输出文件
loglevel = "info" # 日志等级
