[project]
authors = [
  {name = "I Love Study", email = "ilstudy@qq.com"},
]
dependencies = [
    "opencv-python-headless>=4.9.0.80",
    "rich>=13.7.1",
    "rich-argparse>=1.4.0",
]
description = "Default template for PDM package"
license = {text = "LGPL-3.0"}
name = "py-rotaeno-stablizer-gui"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "viztracer>=0.16.2", # performance
    "nuitka>=2.1.3", # packaging
    "yapf>=0.40.2", # formatter
    "pygubu-designer>=0.38", # UI generator
]

[[tool.pdm.autoexport]]
filename = "requirements.txt"
groups = ["default"]
without-hashes = true
