name: Build & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_exe:
    name: Build standlone
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout opencv-python
      uses: actions/checkout@v4
      with:
        repository: opencv/opencv-python
        path: opencv-python
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install UPX
      run: |
        choco install upx
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: 'x64'
        cache: 'pip'
    
    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: rotaeno_stablizer
        mode: standalone
        enable-plugins: upx, tk-inter
        lto: yes
        python-flag: -m
        include-data-files: rotaeno_stablizer/*.png=rotaeno_stablizer/
        include-package-data: CTkMessagebox
        windows-icon-from-ico: rotaeno_stablizer/logo.png

    - name: Copy config.toml to dist
      run: |
        cp config.toml ./build/rotaeno_stablizer.dist

    - name: Turn dist to 7z file
      run: |
        7z a -t7z rotaeno_stablizer.7z -mx=9 ./build/rotaeno_stablizer.dist

    - uses: actions/upload-artifact@v4
      with:
        name: Rotaeno Stablizer
        path: ./rotaeno_stablizer.7z
