name: Build & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_exe:
    name: Build standlone
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout opencv-python
      uses: actions/checkout@v4
      with:
        repository: opencv/opencv-python
        path: opencv-python
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    # 使用UPX会使得内存占用增加 ~100Mb
    #- name: Install UPX
    #  run: |
    #    choco install upx
    
    - name: Install nasm (for libjpeg-turbo in opencv-python)
      uses: ilammy/setup-nasm@v1

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
        cache: 'pip'
    
    # 把 opencv-python-headless 从 requirements.txt 中先去掉再安装
    - name: Pip install
      run: |
        grep -v 'opencv-python-headless' requirements.txt > requirements_.txt
        pip install -r requirements_.txt
      
      # 使用精简版 opencv-python-headless
    - name: Install opencv-python-headless(With only core imgproc and imgcodecs)
      run: |
        mv opencv-python/setup.py opencv-python/setup-original.py
        mv standalone_tools/opencv-setup-hack.py opencv-python/setup.py
        pip install ./opencv-python --verbose

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: rotaeno_stablizer
        standalone: true
        onefile: false
        #enable-plugins: upx

    - name: Move config.toml to dist
      run: |
        mv config.toml ./build/rotaeno_stablizer.dist/config.toml

    - uses: actions/upload-artifact@v4
      with:
        path: |
          ./rotaeno_stablizer.7z

    - name: Turn dist to 7z file
      run: |
        7z a -t7z rotaeno_stablizer.7z -mx=9 ./build/rotaeno_stablizer.dist

    - name: get ffmpeg with lgpl
      run: |
        curl -JLO https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl-shared.zip
        7z x ffmpeg-master-latest-win64-lgpl-shared.zip ffmpeg-master-latest-win64-lgpl-shared/bin/*
        mv ffmpeg-master-latest-win64-lgpl-shared/bin build/rotaeno_stablizer.dist/ffmpeg
        7z a -t7z rotaeno_stablizer_with_ffmpeg.7z -mx=9 ./build/rotaeno_stablizer.dist
  
    - uses: actions/upload-artifact@v4
      with:
        path: |
          ./rotaeno_stablizer_with_ffmpeg.7z
