name: Release Build & Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main_job:
    name: Build Windows Standalone
    runs-on: windows-latest
    permissions:
      id-token: write   # 允许 OIDC token 认证
      contents: write   # 允许读写仓库内容

    steps:
    - uses: actions/checkout@v4
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install UPX
      run: |
        choco install upx

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Install dependencies
      run: pdm install

    # 将 README.md 中的相对路径转换为绝对路径
    - name: Turn reletive link to absolute link in README
      run: pdm run readme_url_replace.py

    - name: Build pypi package & publish
      run: pdm publish --skip-existing

    - name: Build Standalone
      run: |
        pdm run nuitka --standalone rotaeno_stablizer --output-dir=build --python-flag=-m --plugin-enable=upx,tk-inter --lto=yes --include-data-files=rotaeno_stablizer/*.png=rotaeno_stablizer/ --windows-icon-from-ico=rotaeno_stablizer/logo.png --include-package-data=CTkMessagebox --assume-yes-for-downloads

    - name: Copy config.toml to dist
      run: |
        cp config.toml ./build/rotaeno_stablizer.dist

    - name: Turn dist to 7z file
      run: |
        7z a -t7z rotaeno_stablizer_win64.7z -mx=9 ./build/rotaeno_stablizer.dist

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./rotaeno_stablizer_win64.7z